# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wxhaoooo/Documents/lyra

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wxhaoooo/Documents/lyra

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wxhaoooo/Documents/lyra/CMakeFiles /home/wxhaoooo/Documents/lyra/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wxhaoooo/Documents/lyra/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lyra

# Build rule for target.
lyra: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lyra
.PHONY : lyra

# fast build rule for target.
lyra/fast:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/build
.PHONY : lyra/fast

#=============================================================================
# Target rules for targets named alglib

# Build rule for target.
alglib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 alglib
.PHONY : alglib

# fast build rule for target.
alglib/fast:
	$(MAKE) -f deps/alglib/CMakeFiles/alglib.dir/build.make deps/alglib/CMakeFiles/alglib.dir/build
.PHONY : alglib/fast

#=============================================================================
# Target rules for targets named json

# Build rule for target.
json: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 json
.PHONY : json

# fast build rule for target.
json/fast:
	$(MAKE) -f deps/jsoncpp/CMakeFiles/json.dir/build.make deps/jsoncpp/CMakeFiles/json.dir/build
.PHONY : json/fast

src/cloth.o: src/cloth.cpp.o

.PHONY : src/cloth.o

# target to build an object file
src/cloth.cpp.o:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/cloth.cpp.o
.PHONY : src/cloth.cpp.o

src/cloth.i: src/cloth.cpp.i

.PHONY : src/cloth.i

# target to preprocess a source file
src/cloth.cpp.i:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/cloth.cpp.i
.PHONY : src/cloth.cpp.i

src/cloth.s: src/cloth.cpp.s

.PHONY : src/cloth.s

# target to generate assembly for a file
src/cloth.cpp.s:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/cloth.cpp.s
.PHONY : src/cloth.cpp.s

src/conf.o: src/conf.cpp.o

.PHONY : src/conf.o

# target to build an object file
src/conf.cpp.o:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/conf.cpp.o
.PHONY : src/conf.cpp.o

src/conf.i: src/conf.cpp.i

.PHONY : src/conf.i

# target to preprocess a source file
src/conf.cpp.i:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/conf.cpp.i
.PHONY : src/conf.cpp.i

src/conf.s: src/conf.cpp.s

.PHONY : src/conf.s

# target to generate assembly for a file
src/conf.cpp.s:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/conf.cpp.s
.PHONY : src/conf.cpp.s

src/constraint.o: src/constraint.cpp.o

.PHONY : src/constraint.o

# target to build an object file
src/constraint.cpp.o:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/constraint.cpp.o
.PHONY : src/constraint.cpp.o

src/constraint.i: src/constraint.cpp.i

.PHONY : src/constraint.i

# target to preprocess a source file
src/constraint.cpp.i:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/constraint.cpp.i
.PHONY : src/constraint.cpp.i

src/constraint.s: src/constraint.cpp.s

.PHONY : src/constraint.s

# target to generate assembly for a file
src/constraint.cpp.s:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/constraint.cpp.s
.PHONY : src/constraint.cpp.s

src/dde.o: src/dde.cpp.o

.PHONY : src/dde.o

# target to build an object file
src/dde.cpp.o:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/dde.cpp.o
.PHONY : src/dde.cpp.o

src/dde.i: src/dde.cpp.i

.PHONY : src/dde.i

# target to preprocess a source file
src/dde.cpp.i:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/dde.cpp.i
.PHONY : src/dde.cpp.i

src/dde.s: src/dde.cpp.s

.PHONY : src/dde.s

# target to generate assembly for a file
src/dde.cpp.s:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/dde.cpp.s
.PHONY : src/dde.cpp.s

src/geometry.o: src/geometry.cpp.o

.PHONY : src/geometry.o

# target to build an object file
src/geometry.cpp.o:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/geometry.cpp.o
.PHONY : src/geometry.cpp.o

src/geometry.i: src/geometry.cpp.i

.PHONY : src/geometry.i

# target to preprocess a source file
src/geometry.cpp.i:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/geometry.cpp.i
.PHONY : src/geometry.cpp.i

src/geometry.s: src/geometry.cpp.s

.PHONY : src/geometry.s

# target to generate assembly for a file
src/geometry.cpp.s:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/geometry.cpp.s
.PHONY : src/geometry.cpp.s

src/handle.o: src/handle.cpp.o

.PHONY : src/handle.o

# target to build an object file
src/handle.cpp.o:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/handle.cpp.o
.PHONY : src/handle.cpp.o

src/handle.i: src/handle.cpp.i

.PHONY : src/handle.i

# target to preprocess a source file
src/handle.cpp.i:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/handle.cpp.i
.PHONY : src/handle.cpp.i

src/handle.s: src/handle.cpp.s

.PHONY : src/handle.s

# target to generate assembly for a file
src/handle.cpp.s:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/handle.cpp.s
.PHONY : src/handle.cpp.s

src/io.o: src/io.cpp.o

.PHONY : src/io.o

# target to build an object file
src/io.cpp.o:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/io.cpp.o
.PHONY : src/io.cpp.o

src/io.i: src/io.cpp.i

.PHONY : src/io.i

# target to preprocess a source file
src/io.cpp.i:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/io.cpp.i
.PHONY : src/io.cpp.i

src/io.s: src/io.cpp.s

.PHONY : src/io.s

# target to generate assembly for a file
src/io.cpp.s:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/io.cpp.s
.PHONY : src/io.cpp.s

src/magic.o: src/magic.cpp.o

.PHONY : src/magic.o

# target to build an object file
src/magic.cpp.o:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/magic.cpp.o
.PHONY : src/magic.cpp.o

src/magic.i: src/magic.cpp.i

.PHONY : src/magic.i

# target to preprocess a source file
src/magic.cpp.i:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/magic.cpp.i
.PHONY : src/magic.cpp.i

src/magic.s: src/magic.cpp.s

.PHONY : src/magic.s

# target to generate assembly for a file
src/magic.cpp.s:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/magic.cpp.s
.PHONY : src/magic.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mesh.o: src/mesh.cpp.o

.PHONY : src/mesh.o

# target to build an object file
src/mesh.cpp.o:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/mesh.cpp.o
.PHONY : src/mesh.cpp.o

src/mesh.i: src/mesh.cpp.i

.PHONY : src/mesh.i

# target to preprocess a source file
src/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/mesh.cpp.i
.PHONY : src/mesh.cpp.i

src/mesh.s: src/mesh.cpp.s

.PHONY : src/mesh.s

# target to generate assembly for a file
src/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/mesh.cpp.s
.PHONY : src/mesh.cpp.s

src/mot_parser.o: src/mot_parser.cpp.o

.PHONY : src/mot_parser.o

# target to build an object file
src/mot_parser.cpp.o:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/mot_parser.cpp.o
.PHONY : src/mot_parser.cpp.o

src/mot_parser.i: src/mot_parser.cpp.i

.PHONY : src/mot_parser.i

# target to preprocess a source file
src/mot_parser.cpp.i:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/mot_parser.cpp.i
.PHONY : src/mot_parser.cpp.i

src/mot_parser.s: src/mot_parser.cpp.s

.PHONY : src/mot_parser.s

# target to generate assembly for a file
src/mot_parser.cpp.s:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/mot_parser.cpp.s
.PHONY : src/mot_parser.cpp.s

src/physics.o: src/physics.cpp.o

.PHONY : src/physics.o

# target to build an object file
src/physics.cpp.o:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/physics.cpp.o
.PHONY : src/physics.cpp.o

src/physics.i: src/physics.cpp.i

.PHONY : src/physics.i

# target to preprocess a source file
src/physics.cpp.i:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/physics.cpp.i
.PHONY : src/physics.cpp.i

src/physics.s: src/physics.cpp.s

.PHONY : src/physics.s

# target to generate assembly for a file
src/physics.cpp.s:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/physics.cpp.s
.PHONY : src/physics.cpp.s

src/simulation.o: src/simulation.cpp.o

.PHONY : src/simulation.o

# target to build an object file
src/simulation.cpp.o:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/simulation.cpp.o
.PHONY : src/simulation.cpp.o

src/simulation.i: src/simulation.cpp.i

.PHONY : src/simulation.i

# target to preprocess a source file
src/simulation.cpp.i:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/simulation.cpp.i
.PHONY : src/simulation.cpp.i

src/simulation.s: src/simulation.cpp.s

.PHONY : src/simulation.s

# target to generate assembly for a file
src/simulation.cpp.s:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/simulation.cpp.s
.PHONY : src/simulation.cpp.s

src/sparse_solver.o: src/sparse_solver.cpp.o

.PHONY : src/sparse_solver.o

# target to build an object file
src/sparse_solver.cpp.o:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/sparse_solver.cpp.o
.PHONY : src/sparse_solver.cpp.o

src/sparse_solver.i: src/sparse_solver.cpp.i

.PHONY : src/sparse_solver.i

# target to preprocess a source file
src/sparse_solver.cpp.i:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/sparse_solver.cpp.i
.PHONY : src/sparse_solver.cpp.i

src/sparse_solver.s: src/sparse_solver.cpp.s

.PHONY : src/sparse_solver.s

# target to generate assembly for a file
src/sparse_solver.cpp.s:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/sparse_solver.cpp.s
.PHONY : src/sparse_solver.cpp.s

src/spline.o: src/spline.cpp.o

.PHONY : src/spline.o

# target to build an object file
src/spline.cpp.o:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/spline.cpp.o
.PHONY : src/spline.cpp.o

src/spline.i: src/spline.cpp.i

.PHONY : src/spline.i

# target to preprocess a source file
src/spline.cpp.i:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/spline.cpp.i
.PHONY : src/spline.cpp.i

src/spline.s: src/spline.cpp.s

.PHONY : src/spline.s

# target to generate assembly for a file
src/spline.cpp.s:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/spline.cpp.s
.PHONY : src/spline.cpp.s

src/transformation.o: src/transformation.cpp.o

.PHONY : src/transformation.o

# target to build an object file
src/transformation.cpp.o:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/transformation.cpp.o
.PHONY : src/transformation.cpp.o

src/transformation.i: src/transformation.cpp.i

.PHONY : src/transformation.i

# target to preprocess a source file
src/transformation.cpp.i:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/transformation.cpp.i
.PHONY : src/transformation.cpp.i

src/transformation.s: src/transformation.cpp.s

.PHONY : src/transformation.s

# target to generate assembly for a file
src/transformation.cpp.s:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/transformation.cpp.s
.PHONY : src/transformation.cpp.s

src/util.o: src/util.cpp.o

.PHONY : src/util.o

# target to build an object file
src/util.cpp.o:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/util.cpp.o
.PHONY : src/util.cpp.o

src/util.i: src/util.cpp.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

src/vectors.o: src/vectors.cpp.o

.PHONY : src/vectors.o

# target to build an object file
src/vectors.cpp.o:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/vectors.cpp.o
.PHONY : src/vectors.cpp.o

src/vectors.i: src/vectors.cpp.i

.PHONY : src/vectors.i

# target to preprocess a source file
src/vectors.cpp.i:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/vectors.cpp.i
.PHONY : src/vectors.cpp.i

src/vectors.s: src/vectors.cpp.s

.PHONY : src/vectors.s

# target to generate assembly for a file
src/vectors.cpp.s:
	$(MAKE) -f CMakeFiles/lyra.dir/build.make CMakeFiles/lyra.dir/src/vectors.cpp.s
.PHONY : src/vectors.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... lyra"
	@echo "... edit_cache"
	@echo "... alglib"
	@echo "... json"
	@echo "... src/cloth.o"
	@echo "... src/cloth.i"
	@echo "... src/cloth.s"
	@echo "... src/conf.o"
	@echo "... src/conf.i"
	@echo "... src/conf.s"
	@echo "... src/constraint.o"
	@echo "... src/constraint.i"
	@echo "... src/constraint.s"
	@echo "... src/dde.o"
	@echo "... src/dde.i"
	@echo "... src/dde.s"
	@echo "... src/geometry.o"
	@echo "... src/geometry.i"
	@echo "... src/geometry.s"
	@echo "... src/handle.o"
	@echo "... src/handle.i"
	@echo "... src/handle.s"
	@echo "... src/io.o"
	@echo "... src/io.i"
	@echo "... src/io.s"
	@echo "... src/magic.o"
	@echo "... src/magic.i"
	@echo "... src/magic.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mesh.o"
	@echo "... src/mesh.i"
	@echo "... src/mesh.s"
	@echo "... src/mot_parser.o"
	@echo "... src/mot_parser.i"
	@echo "... src/mot_parser.s"
	@echo "... src/physics.o"
	@echo "... src/physics.i"
	@echo "... src/physics.s"
	@echo "... src/simulation.o"
	@echo "... src/simulation.i"
	@echo "... src/simulation.s"
	@echo "... src/sparse_solver.o"
	@echo "... src/sparse_solver.i"
	@echo "... src/sparse_solver.s"
	@echo "... src/spline.o"
	@echo "... src/spline.i"
	@echo "... src/spline.s"
	@echo "... src/transformation.o"
	@echo "... src/transformation.i"
	@echo "... src/transformation.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... src/vectors.o"
	@echo "... src/vectors.i"
	@echo "... src/vectors.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

